- lib/src/definitions/validation/thing_description_schema.dart
This PR updates the JSON Schema definition for Thing Descriptions to the [latest version](https://github.com/w3c/wot-thing-description/blob/a53f21574d8b071e3e631f487b68363a7b5d709e/validation/td-json-schema-validation.json) published in the WoT TD repository.
The most important change for us is the support for additional security schemes, like ACE-OAuth (c.f., #8).
> feat: update TD JSON Schema

- lib/src/binding_coap/coap_extensions.dart
- lib/src/binding_http/http_server.dart
This PR fixes some minor style issues pointed out by the linter.
> style: address linting issues

- lib/src/definitions/interaction_affordances/action.dart
This PR cleans up a couple of leftovers from #18.
> style: address remaining linting issues

- example/coaps_readproperty.dart
- lib/src/binding_coap/coap_client.dart
- lib/src/binding_coap/coap_definitions.dart
- lib/src/binding_coap/coap_extensions.dart
- lib/src/core/codecs/link_format_codec.dart
- lib/src/core/credentials/psk_credentials.dart
- lib/src/core/security_provider.dart
- pubspec.yaml
This PR adjusts the CoAP binding [CoAP library](https://github.com/shamblett/coap)'s new API. It is still WIP as a new CoAP version has not been published yet.
Once this PR is merged, #17 can be rebased against the new `main` branch.
> feat: adjust CoAP binding to new library API

- lib/core.dart
- lib/src/binding_coap/coap_client.dart
- lib/src/binding_coap/coap_extensions.dart
- lib/src/core/credentials/ace_credentials.dart
- lib/src/core/security_provider.dart
- lib/src/definitions/security/ace_security_scheme.dart
- lib/src/definitions/thing_description.dart
- pubspec.yaml
- test/core/definitions_test.dart
This PR adds ACE-OAuth support to the library. It depends on #3.
> feat(binding-coap): add ACE-OAuth support

- README.md
- example/example.dart
- lib/binding_mqtt.dart
- lib/dart_wot.dart
- lib/src/binding_mqtt/constants.dart
- lib/src/binding_mqtt/mqtt_binding_exception.dart
- lib/src/binding_mqtt/mqtt_client.dart
- lib/src/binding_mqtt/mqtt_client_factory.dart
- lib/src/binding_mqtt/mqtt_config.dart
- lib/src/binding_mqtt/mqtt_extensions.dart
- lib/src/binding_mqtt/mqtt_subscription.dart
- pubspec.yaml
This PR adds the first version of an MQTT binding to the project.
> feat: add first version of MQTT binding

- example/complex_example.dart
- lib/src/binding_coap/coap_client.dart
- lib/src/binding_coap/coap_definitions.dart
- lib/src/binding_coap/coap_extensions.dart
- lib/src/definitions/context_entry.dart
- test/binding_coap/coap_vocabulary_test.dart
This PR implements initial support for the new [CoAP Protocol Binding Template](https://w3c.github.io/wot-binding-templates/bindings/protocols/coap/index.html).
> feat: implement new CoAP vocabulary terms

- lib/src/core/consumed_thing.dart
- lib/src/definitions/form.dart
This PR addresses a minor linting issue in the `Form` class.
> chore(form): address linting issue

- example/coap_dns_sd_discovery.dart
- lib/binding_coap.dart
- lib/binding_http.dart
- lib/binding_mqtt.dart
- lib/core.dart
- lib/definitions.dart
- lib/scripting_api.dart
- lib/src/binding_coap/coap_extensions.dart
This PR addresses a few linting issues and bugs pointed out by static analysis.
> chore: address linting issues

- example/coaps_readproperty.dart
- lib/src/binding_coap/coap_client.dart
- lib/src/core/content_serdes.dart
- lib/src/core/security_provider.dart
- lib/src/definitions/form.dart
- lib/src/definitions/validation/thing_description_schema.dart
- pubspec.yaml
This PR upgrades most of the dependencies to their latest version and adapts the CoAP binding to the latest API changes in the `coap` package.
> chore!: upgrade dependencies

- pubspec.yaml
This PR updates the package's dependencies to their latest version.
> chore(deps): update dependencies

- pubspec.yaml
This PR updates the homepage URL in the `pubspec.yaml` file so that it points to the new repository location.
> chore(pubspec.yaml): update homepage URL

- .github/workflows/ci.yml
> ci: remove token from codecov upload step

- lib/src/core/implementation/thing_discovery.dart
This PR improves the performance of the CoRE resource discovery implementation by executing the retrieval of Thing Descriptions concurrently.
Testing the new implementation with the `core_link_format_discovery.dart` example indicates that the changes already improve the performance by a factor of 2 for four medium-sized Thing Descriptions. For larger lists of Thing Descriptions, the performance gains should even be larger.
> refactor: improve performance of CoRE resource discovery

- .github/workflows/publish.yaml
- CHANGELOG.md
> chore: switch to automated publishing workflow

- CHANGELOG.md
- pubspec.yaml
This PR prepares the first release that is going to use the new automated publishing workflow. Let's hope that it will work 🤞
> chore(release): prepare release 0.28.2

- test/core/wot_test.dart
This PR makes the Dart analyzer a bit happier.
> style(tests): add a missing trailing comma

- CHANGELOG.md
- pubspec.yaml
This PR prepares a new minor release.
> chore(release): prepare release 0.29.0

- CONTRIBUTING.md
> chore(CONTRIBUTING.md): fix typos

- lib/src/binding_mqtt/mqtt_client.dart
- lib/src/binding_mqtt/mqtt_extensions.dart
- lib/src/core/definitions/extensions/json_parser.dart
- lib/src/core/implementation/thing_discovery.dart
- test/core/thing_description_test.dart
- test/core/wot_test.dart
In addition to #151, I noticed a number of further style issues around the codebase which are going to be fixed by this PR.
> Fix typos and style issues

- README.md
As discussed in today's call, this PR adds the information regarding adopters to the README.
> docs(README): add Adopters section and badge
