eclipse-thingweb/dart_wot

lib/src/binding_coap/coap_client.dart
This PR lets the CoAP client use the correct setter for a request's URI path. This allows us to get rid of two `ignore` comments for the linter.
=> fix(coap_client): correctly set URI path for discovery

lib/src/binding_coap/coap_client.dart
Previously, the Content-Format `text/plain` was used in an Accept option for discovery with the CoRE Link Format. This PR changes the Content-Format used to `application/link-format` (Content-Format 40) in order to avoid rejection by other implementations.
=> fix(coap_client): set accept to application/link-format for CoRE Link Format discovery

lib/src/core/codecs/codec_media_type.dart, lib/src/core/content_serdes.dart, test/core/content_serdes_test.dart
This PR simplifies the system used for assigning content types to codecs. The new system does not require a manual assignment anymore, but determines the Codec that is supposed to be used by using a simple algorithm, using both the primary and the "main" subtype (e.g., `json` or `cbor`) for the assignment.
=> refactor(core): simplify codec registration system

lib/src/core/codecs/link_format_codec.dart, lib/src/core/content_serdes.dart, test/core/content_serdes_test.dart
This PR adds a Codec for the CoRE Link Format. The logic is taken from the CoAP library used by dart_wot.
=> feat: add Codec for CoRE Link Format

lib/src/binding_coap/coap_client.dart, lib/src/binding_coap/coap_definitions.dart, lib/src/binding_coap/coap_extensions.dart, lib/src/binding_http/http_client.dart, lib/src/core/protocol_interfaces/protocol_client.dart, lib/src/core/thing_discovery.dart
This PR reworks the internal Discovery API, separating the different library modules more cleanly and allowing the addition of further TD Media Types (such as CBOR or XML) in the future. The PR also greatly improves the CoAP binding, potentially allowing for secure discovery using ACE-OAuth as a follow-up (see #6).
=> refactor!: rework internal Discovery API and CoAP Binding

lib/src/definitions/form.dart
This PR adds support for the [`contentCoding` field](https://w3c.github.io/wot-thing-description/#td-vocab-contentCoding--Form) to the `Form` class, which was missing before.
=> feat: add missing contentCoding field to form

.github/workflows/ci.yml
This PR improves the CI by letting the tests run on all three major platforms (Linux, macOS, and Windows).
=> chore(ci): also run CI on macOS and Windows

lib/src/definitions/thing_description.dart, lib/src/definitions/validation/thing_description_schema.dart
Calling `toString()` on the `ThingDescriptionValidationException` now returns a formatted list of all validation errors.
=> feat: improve `ThingDescriptionValidationException`

example/complex_example.dart, example/http_basic_authentication.dart, lib/src/binding_http/http_client.dart, lib/src/core/security_provider.dart, test/binding_http/http_test.dart
Passing invalid Credentials after a failed authorization/authentication process allows users to try again with different credentials, once it is supported by the binding implementations.
=> feat!: allow passing invalid credentials to security callbacks

lib/src/binding_coap/coap_binding_exception.dart, lib/src/binding_coap/coap_client.dart, lib/src/binding_coap/coap_extensions.dart
I noticed that the CoAP binding is not handling error responses correctly at the moment. This PR applies some refactoring and introduces an additional check for error responses.
=> fix(binding-coap): improve reponse error handling

lib/src/definitions/context_entry.dart
This PR fixes a small bug that was introduced by #28, causing errors when encountering a string-based @context entry after the first one.
=> fix: correctly parse String `@context` entries

example/complex_example.dart, example/example.dart, example/http_basic_authentication.dart, lib/src/binding_mqtt/mqtt_extensions.dart, lib/src/definitions/additional_expected_response.dart, lib/src/definitions/data_schema.dart, lib/src/definitions/expected_response.dart, lib/src/definitions/extensions/json_parser.dart, lib/src/definitions/form.dart, lib/src/definitions/interaction_affordances/action.dart, lib/src/definitions/interaction_affordances/event.dart, lib/src/definitions/interaction_affordances/interaction_affordance.dart, lib/src/definitions/interaction_affordances/property.dart, lib/src/definitions/link.dart, lib/src/definitions/security/ace_security_scheme.dart, lib/src/definitions/security/apikey_security_scheme.dart, lib/src/definitions/security/auto_security_scheme.dart, lib/src/definitions/security/basic_security_scheme.dart, lib/src/definitions/security/bearer_security_scheme.dart, lib/src/definitions/security/digest_security_scheme.dart, lib/src/definitions/security/no_security_scheme.dart, lib/src/definitions/security/oauth2_security_scheme.dart, lib/src/definitions/security/psk_security_scheme.dart, lib/src/definitions/security/security_scheme.dart, lib/src/definitions/thing_description.dart, lib/src/definitions/version_info.dart, test/core/content_serdes_test.dart, test/core/definitions_test.dart
This PR applies a number of additional reworks to the `definitions` module. It applies a number of refactorings for a more elegant processing of JSON to the module's class system and adds missing fields to the classes, achieving a complete mapping of the WoT TD data structures. Furthermore, it improves the support for additional fields in the different TD subclasses and expansions via JSON-LD.
=> Refactor and fix data schemas and TD parsing

lib/src/binding_coap/coap_extensions.dart, lib/src/definitions/operation_type.dart
For some reason, this operation type was missing from the `OperationType` enumeration.
=> fix(definitions): add missing writeallproperties operation

lib/src/binding_coap/coap_client.dart, lib/src/binding_coap/coap_extensions.dart, lib/src/binding_http/http_client.dart, lib/src/binding_mqtt/mqtt_client.dart, lib/src/core/content.dart, lib/src/core/protocol_interfaces/protocol_client.dart, lib/src/core/thing_discovery.dart
I noticed a couple of issues when trying to use CoAP multicast for discovery from `/.well-known/core`. This PR provides a fix by introducing a subclass of `Content` called `DiscoveryContent` which makes it possible to follow up to a multicast request with a unicast request.
=> feat!: improve multicast discovery with CoRE Link-Format

test/binding_coap/binding_coap_test.mocks.dart, test/binding_http/http_test.mocks.dart
This trivial PR fixes a linting problem that occurs with the current Dart version.
=> style: fix formatting of mocked classes

example/coaps_readproperty.dart, lib/src/binding_coap/coap_client.dart, lib/src/binding_coap/coap_config.dart, lib/src/binding_coap/coap_extensions.dart, pubspec.yaml
This PR updates the `coap` package to the latest version, which removes `dart_tinydtls` as dependency. While the general feature set stays the same, it implies a breaking change since config parameters need to be changed and (due to a bug in the `dtls2` package) the subset of available ciphers needs to be adjusted.
=> feat!: update `coap` dependency, fix example

.github/workflows/ci.yml
I noticed that the code coverage report generation can be done in only line. This PR applies the change to the CI.
=> chore: simplify code coverage generation

example/coap_discovery.dart, example/complex_example.dart, example/core_link_format_discovery.dart, example/example.dart, lib/src/core/thing_discovery.dart, lib/src/core/wot.dart, lib/src/scripting_api/discovery/thing_discovery.dart, lib/src/scripting_api/discovery/thing_filter.dart, lib/src/scripting_api/wot.dart
This PR reworks the discovery API slightly (but in a breaking way), moving the `uri` argument from the `ThingFilter` class to the `discover` method itself.
There will probably another round of breaking changes once the discovery API in the Scripting API specification has been finalized, but this change should already be a significant improvement.
=> feat!: rework discovery API

.github/workflows/ci.yml
This PR should make it possible to properly use the new merge queue feature.
=> chore(ci): enable GitHub Actions for merge queue

example/coap_dns_sd_discovery.dart, lib/src/core/thing_discovery.dart, lib/src/scripting_api/discovery/discovery_method.dart, pubspec.yaml
This PR includes a first approach to supporting DNS-DS discovery, as specified in [section 6.3](https://w3c.github.io/wot-discovery/#introduction-dns-sd-sec) of the WoT Discovery specification.
For now, only discovery using mDNS is supported.
=> feat: implement initial DNS-SD support

lib/src/binding_coap/coap_extensions.dart, test/binding_coap/coap_vocabulary_test.dart
This PR incorporates the changes made in https://github.com/w3c/wot-binding-templates/pull/259 into the CoAP binding implementation.
=> feat(binding-coap)!: use blockSize instead of blockSZX

lib/src/core/credentials/ace_credentials.dart, lib/src/core/credentials/apikey_credentials.dart, lib/src/core/credentials/basic_credentials.dart, lib/src/core/credentials/bearer_credentials.dart, lib/src/core/credentials/credentials.dart, lib/src/core/credentials/digest_credentials.dart, lib/src/core/credentials/oauth2_credentials.dart, lib/src/core/credentials/psk_credentials.dart
I noticed that the `SecurityScheme` and the respective `Credentials` classes actually do not need to be coupled as tightly as they are at the moment. Therefore, this PR decouples them.
=> refactor: decouple credentials and security scheme classes

lib/src/definitions/security/psk_security_scheme.dart, lib/src/definitions/security/security_scheme.dart, test/core/consumed_thing_test.dart
This PR changes the `proxy` field in the `SecurityScheme` class to use the more appropriate `Uri` type and adds missing documentation.
=> feat!(security_scheme): use `Uri` instead of `String` for proxy field

lib/src/definitions/security/combo_security_scheme.dart, lib/src/definitions/security/security_scheme.dart, test/core/consumed_thing_test.dart
This PR adds the currently missing `ComboSecurityScheme` as a new feature. The implementation will be slightly adjusted in the context of #44.
=> feat: add ComboSecurityScheme

lib/src/definitions/extensions/json_parser.dart, lib/src/definitions/security/ace_security_scheme.dart, lib/src/definitions/security/apikey_security_scheme.dart, lib/src/definitions/security/auto_security_scheme.dart, lib/src/definitions/security/basic_security_scheme.dart, lib/src/definitions/security/bearer_security_scheme.dart, lib/src/definitions/security/combo_security_scheme.dart, lib/src/definitions/security/digest_security_scheme.dart, lib/src/definitions/security/no_security_scheme.dart, lib/src/definitions/security/oauth2_security_scheme.dart, lib/src/definitions/security/psk_security_scheme.dart, lib/src/definitions/security/security_scheme.dart
This PR refactors the deserialization of the different `SecurityScheme` sub-classes, making the implementation more null-safe.
=> refactor!: rework deserialization of security schemes

lib/src/scripting_api/interaction_options.dart
This PR improves the reliability of the `InteractionOptions` class by making itself `immutable` and its fields `final`.
=> feat(scripting_api): make InteractionOptions immutable

example/complex_example.dart
This PR addresses a (relatively trivial) linting issue.
=> style: use const constructor in complex_example

lib/src/definitions/validation/thing_description_schema.dart
This PR updates the JSON Schema definition to the latest version provided in the TD repository (also see https://github.com/w3c/wot-thing-description/pull/1786).
=> feat: update JSON Schema definition to latest version

CHANGELOG.md
For some reason, the formatting of the CHANGELOG file got messed up over the course of the last releases. This PR properly reformats the file again.
=> chore: fix CHANGELOG formatting

lib/src/binding_coap/coap_client.dart, lib/src/binding_http/http_client.dart, lib/src/binding_mqtt/mqtt_client.dart, lib/src/core/codecs/cbor_codec.dart, lib/src/core/codecs/content_codec.dart, lib/src/core/codecs/json_codec.dart, lib/src/core/codecs/link_format_codec.dart, lib/src/core/content.dart, lib/src/core/content_serdes.dart
This PR makes the internal handling of the `Content` class easier by allowing for the conversion of streams into lists of (unsigned) integers instead of buffers, which gets rid of a few conversion steps.
=> Improve `Content` APIs

.gitlab-ci.yml, pubspec.yaml
As the `dart_code_metrics` is about to be deprecated (see, e.g., its [pub.dev page](https://pub.dev/packages/dart_code_metrics)), this PR proposes removing it from the `pubspec.yaml` file.
Since `dart_code_metrics` depends on the `http` package, the dependency currently is a blocker for upgrading the `http` package for `dart_wot`, which is resolved by the removal.
=> chore: remove `dart_code_metrics` dev dependency

lib/src/core/thing_discovery.dart
Noticed that the logic that is used to determine whether a discovered URI is a duplicate has been reversed so far. This PR applies a simple fix.
=> fix: fix duplicate URI detection during MDNS discovery

README.md
Similarly to #69, this PR updates the URLs used in badges within the README file.
For the codecov badge to continue working, we may need to update the secret associated with this repository (see [here](https://app.codecov.io/gh/eclipse-thingweb/dart_wot/new)).
=> chore: update URLs in README badges

example/coaps_readproperty.dart, example/complex_example.dart, example/example.dart, example/http_basic_authentication.dart, lib/src/binding_coap/coap_extensions.dart, lib/src/core/content_serdes.dart, lib/src/definitions/extensions/json_parser.dart, lib/src/definitions/validation/thing_description_schema.dart, test/binding_coap/coap_vocabulary_test.dart, test/core/dart_wot_test.dart, test/core/definitions_test.dart
This PR applies a number of trailing commas to make the CI a bit happier :)
=> style: apply trailing comma linting suggestions

test/binding_coap/binding_coap_test.dart, test/binding_coap/coap_vocabulary_test.dart
In two test files for CoAP, the wrong license header was being used. This PR updates the headers so that the two files are using the same as all of the other files in the project.
=> chore: use correct license header for CoAP test files

lib/src/definitions/validation/thing_description_schema.dart
This PR incorporates the changes made in https://github.com/w3c/wot-thing-description/pull/1917, https://github.com/w3c/wot-thing-description/pull/1844, and https://github.com/w3c/wot-thing-description/pull/1828 into the JSON Schema definitions.
=> feat: update TD 1.1 JSON Schema to final version

README.md, example/coap_discovery.dart, example/coap_dns_sd_discovery.dart, example/coaps_readproperty.dart, example/complex_example.dart, example/core_link_format_discovery.dart, example/example.dart, example/http_basic_authentication.dart, lib/src/core/servient.dart, test/binding_http/http_test.dart, test/core/consumed_thing_test.dart, test/core/servient_test.dart
This PR makes a couple of improvements with regard to the handling of `ProtocolClientFactories` by introducing a dedicated `clientFactories` constructor parameter, adding a `removeClientFactory` method, improving the documentation, and refactoring some of the examples and test code.
=> feat(servient): improve handling of client factories

README.md, example/example.dart, example/mqtt_example.dart, lib/src/binding_coap/coap_client.dart, lib/src/binding_http/http_client.dart, lib/src/binding_mqtt/mqtt_client.dart, lib/src/core/protocol_interfaces/protocol_client.dart, lib/src/core/servient.dart, lib/src/core/wot.dart, lib/src/scripting_api/wot.dart, test/core/discovery_test.dart
This PR is a first step towards aligning the discovery implementation closer with the Scripting API specification. Based on this PR, it should eventually also be possible to demonstrate some of the open questions I have with regard to covering features like DNS-SD or CoRE RD support from the Discovery Specification.
=> feat: implement requestThingDescription method

lib/src/core/thing_discovery.dart, lib/src/core/wot.dart, lib/src/definitions/thing_description.dart, lib/src/scripting_api/discovery/thing_discovery.dart, lib/src/scripting_api/wot.dart, test/core/discovery_test.dart
=> feat: implement exploreDirectory method

codecov.yml
This PR adds a stricter configuration file for codecov, making it mandatory for new lines of code to be covered by tests while disallowing a decrease in code coverage.
=> ci: add `codecov.yml` file

lib/src/definitions/extensions/json_parser.dart
The temporary TD @context URI `http://www.w3.org/ns/td` is not supported anymore. Therefore, this PR removes it from the list of valid URIs that is used during the (de)serialization process.
=> fix: remove temporary TD context URI

lib/src/binding_coap/coap_extensions.dart, lib/src/binding_http/http_request_method.dart, lib/src/definitions/extensions/json_parser.dart, lib/src/definitions/version_info.dart
I noticed that a couple of files are currently missing copyright headers. This PR adds headers with the correct creation year to the respective files.
=> Add missing copyright headers

example/complex_example.dart, example/http_basic_authentication.dart, example/mqtt_example.dart, lib/src/core/credentials/ace_credentials.dart, lib/src/core/credentials/apikey_credentials.dart, lib/src/core/credentials/basic_credentials.dart, lib/src/core/credentials/bearer_credentials.dart, lib/src/core/credentials/credentials.dart, lib/src/core/credentials/digest_credentials.dart, lib/src/core/credentials/oauth2_credentials.dart, lib/src/core/credentials/psk_credentials.dart, test/binding_http/http_test.dart
This PR applies the `@immutable` annotation to the `Credentials` base class and makes the necessary adjustments in the inheriting classes regarding immutability to make the library more reliable and slightly increase its performance.
=> feat!: make credentials classes immutable

lib/src/core/implementation/augmented_form.dart, test/core/augmented_form_test.dart
The logic for validating URI variables has been a bit too strict, preventing all interactions when a value for a URI variable was not provided by the user, for example in the case of the experimental extension of the `exploreDirectory` discovery method in #94.
As also already briefly discussed in https://github.com/w3c/wot-scripting-api/issues/528, the handling of URI variables needs to be improved in general, so this topic should be revisited in future PRs.
=> fix: fix handling of uri variables

example/directory_discovery.dart, lib/src/core/implementation/wot.dart, lib/src/core/scripting_api/wot.dart, test/core/discovery_test.dart
As currently discussed in https://github.com/w3c/wot-scripting-api/issues/528, this PR adds initial experimental support for the three query parameters `offset`, `limit`, and `format` to the `exploreDirectory` method.
At the moment only the `format` value `array` is supported, with the value `collection` left open for a follow-up PR. While implementing, however, I noticed that the current approach does not allow for an elegant passing of the `next` links (from the HTTP response headers) to the upper layers of the library.
Not only in the context of `dart_wot` but also for `node-wot` we could therefore discuss expanding the `Content` class/interface to be able to pass this information alongside the payload data. However, there is probably some discussion needed to do this in a …
=> feat!: add initial support for query parameters to exploreDirectory method

lib/src/binding_coap/coap_definitions.dart, test/binding_coap/coap_definitions_test.dart
This PR adds a static method named `tryParse` to the `CoapSubprotocol` enhanced enum that makes it possible to generate enum values from strings if the string value is known. Otherwise, the method returns `null`.
=> feat(binding_coap): add tryParse method to CoapSubprotocol

example/complex_example.dart, lib/src/binding_coap/coap_client_factory.dart, lib/src/binding_http/http_client_factory.dart, lib/src/binding_mqtt/mqtt_client_factory.dart, lib/src/core/implementation/consumed_thing.dart, lib/src/core/implementation/protocol_interfaces/protocol_client_factory.dart, lib/src/core/implementation/servient.dart, test/binding_coap/coap_client_factory_test.dart, test/binding_http/http_client_factory_test.dart, test/binding_mqtt/mqtt_client_factory_test.dart, test/core/discovery_test.dart, test/core/servient_test.dart
This PR adds new methods called `supportsOperation` to the codebase, which are used to indicate whether a protocol's clients support a given combination of `OperationType` and `subprotocol`.
This solves an issue I've experienced when trying to interact with things that support both CoAP and HTTP for observing properties or subscribing to events, as the long-polling subprotocol is not implemented for dart_wot's HTTP client yet. Therefore, the client could throw an exception since the filtering mechanism was not sufficient enough for the `Servient` to simply ignore those unsupported forms.
The newly added methods should this problem for now. However, as more parameters might need to be added to the respective methods, I've labeled the methods as `@experimental` for now in order to indicate …
=> feat!: add supportsOperation method

lib/src/core/implementation/consumed_thing.dart, lib/src/core/implementation/servient.dart, test/core/servient_test.dart
This PR removes the `hasClientFor` method from the `Servient` class and other classes that depend on it. In the context of #96, I noticed that this method is not really needed. Therefore, this PR cleans up the codebase a bit by relying on the `clientSchemes` getter instead.
=> chore!(servient): remove `hasClientFor` method

lib/src/core/implementation/thing_discovery.dart
This PR includes a rather trivial refactoring of the `ThingDiscovery` implementation's `_clientForUriScheme` method, replacing the unneeded `var` with an immutable `final` keyword.
=> refactor(thing_discovery): refactor _clientForUriScheme

README.md
Similar to https://github.com/eclipse-thingweb/node-wot/pull/1218, this PR adds the new logo to the README file :)
=> docs: add new dart_wot logo to README

lib/src/core/implementation/thing_discovery.dart
After the merge of #103, the extension mentioned above has become obsolete. This PR removes it.
=> refactor: remove obsolete _FlatStreamExtension

lib/src/core/implementation/thing_discovery.dart
Attribute values used during discovery with the CoRE Link Format currently need special treatment. To ensure a uniform behavior, this PR introduces a dedicated extension for formatting the strings in question. This is currently necessary due to a gap in the upstream `coap` library. Once the upstream issue is resolved, the extension can be removed again.
=> refactor: introduce extension for CoRE Link-Format attribute values

lib/src/core/implementation/servient.dart
This PR fixes an oversight in the return type of the `Servient`'s `start()` method, which did not return the Scripting API subpackage's `WoT` _interface_ but the `WoT` _implementation_. When merged, this PR resolves the issue, creating a cleaner API surface.
=> fix(servient): use WoT interface as start() return type

lib/src/core/implementation/servient.dart
When using the `WoT` interface's `consume` method, you are not supposed to be able to consume the same Thing Description twice (although this is probably debatable). Due to an oversight (checking the wrong internal `Map`), this behavior has not been enforced so far, which is corrected by this PR.
=> fix(servient): check the correct map during addConsumedThing

lib/src/core/implementation/interaction_output.dart
This PR refactors the internal `_value` field of the `InteractionOutput` implementation to use the `DataSchemaValue` type instead of a custom record type.
=> refactor(InteractionOutput): use DataSchemaValue internally

lib/src/core/exceptions.dart, lib/src/core/exceptions/web_idl.dart, lib/src/core/implementation/interaction_output.dart, lib/src/core/scripting_api/interaction_output.dart, test/core/exceptions_test.dart, test/core/interaction_output_test.dart
This PR incorporates some of the changes discussed in https://github.com/eclipse-thingweb/node-wot/issues/1221 and https://github.com/w3c/wot-scripting-api/pull/534 into the implementation of the `InteractionOutput` interface, while also aligning it a bit closer to the specification and improving both tests and documentation.
There is still some work to be done, especially when it comes to the recent comments in https://github.com/w3c/wot-scripting-api/pull/534, therefore at least one follow-up PR can be expected soon.
=> feat!: improve InteractionOutput implementation

lib/src/core/definitions/extensions/json_parser.dart, lib/src/core/exceptions.dart, lib/src/core/exceptions/web_idl.dart, lib/src/core/implementation/content_serdes.dart, lib/src/core/implementation/interaction_output.dart, lib/src/core/implementation/wot.dart, test/core/exceptions_test.dart
This PR applies the `immutable` annotation to the `DartWotException` base class for custom exceptions, while applying the `const` modifier for custom exceptions where possible.
=> feat!: make custom exceptions immutable

README.md, example/example.dart
This PR adds some changes to the main example to reflect the latest changes to the codebase in terms of form selection and the explicit support for the `cov:observe` subprotocol. For this PR to work, some upstream changes in node-wot are needed which are hopefully going to be merged soon. Until then, this PR will be put on hold.
=> chore: adjust main example

CHANGELOG.md
As mentioned in https://github.com/eclipse-thingweb/dart_wot/pull/114#issuecomment-2081664179, this PR introduces a new format for the `CHANGELOG` file based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) to make changelogs a bit more readable in the future.
So far, only (some of) the most recent changes are described in this new format, but the goal should probably to apply the new format also to older releases. I am not sure yet whether I am going to this in this PR yet, though.
=> chore(CHANGELOG): switch to the keep a changelog format

.github/workflows/ci.yml
On Windows, the CI currently gets stuck when using the latest version (3.4.0) of the Dart SDK. This PR adds a temporary workaround, using version 3.3.0 on Windows instead. Once https://github.com/dart-lang/sdk/issues/55745 has been resolved, this change should be reverted.
=> ci: use Dart 3.3.0 for Windows

CHANGELOG.md
While adding git tags that were missing to have actually working links from the CHANGELOG.md file, I noticed that the link to the initial release was pointing to the wrong repository. This PR fixes the issue.
(The filling of the git tag gaps will make it possible to finally switch to the [automated release procedure](https://dart.dev/tools/pub/automated-publishing), that is going to be added via #118.)
As suggested in the last committer meeting (CC @relu91), I took a look into automatically generating changelogs via the conventional-changelog CLI and realized that this is probably the best way forward. I will probably make a new release shortly with the current approach that will fix the links in the changelog on pub.dev, but then switch to the conventional changelog afterward.
=> chore(CHANGELOG.md): use correct link to initial release

CHANGELOG.md, pubspec.yaml
This PR prepares the release of a new patch release. This will be the first release to use the Keep a Changelog format, and hopefully the last release to use a manual style of changelog generation. In any case, the project's changelog should now be in a much better shape than it was before :)
=> chore: prepare release 0.28.1

CHANGELOG.md, pubspec.yaml
This PR updates the `lints` package to the latest version.
=> chore(deps-dev): upgrade lints to version 4.0.0

.github/workflows/prevent-fixup.yaml
To prevent the merge of `fixup!` commits in the future, this PR adds a simple GitHub Actions workflow that exists with an error if there should be any commits on the branch whose message starts with `fixup!`. The solution is not that ideal yet, but might get improved at a later point in time.
=> ci: prevent accidental merge of fixup! commits

analysis_options.yaml
The API of the `lint` package that is used for static analysis has changed some time ago. This PR updates the import that is being used accordingly.
=> chore: update deprecated import from lint package

analysis_options.yaml
The `analysis_options.yaml` file still contained a number of unused or commented out configuration, both for the linter and for `dart_code_metrics` which has actually been removed a long time ago. This PR performs some cleanup and removes the unused contents from the file.
=> Clean up `analysis_options.yaml`

CONTRIBUTING.md, README.md
This PR expands the contribution guidelines for the repository and aligns them with the other Thingweb repos. It also removes old, obsolete information from the `README` file.
For now, I just copied over parts of the guidelines from node-wot and will add more project-specific information in subsequent PRs. I hope this fine, @danielpeintner, @relu91, and @egekorkan, otherwise please let me know :)
=> Improve contribution guidelines

lib/src/core/definitions/thing_description.dart, test/core/thing_description_test.dart
This PR adds a very basic implementation for the “conversion” of a `ThingDescription` to a `Map<String, dynamic>` object via the `toJson` method. This is done by keeping a reference to the `Map` object that is being passed into the named `fromJson` constructor.
The implementation is not the most elegant and should be reworked/made more efficient in follow-up PRs; however, for now it closes a gap that caused an `UnimplementedError` to be thrown until now when someone would have called that method, crashing the application, which is not really desirable. Therefore, this PR makes the library a bit more usable in practice.
=> feat(thing_description.dart): add basic toJson implementation

CONTRIBUTING.md
To document the current process that is used to generate new releases, this PR adds an explainer section to the `CONTRIBUTING.md` file.
Hopefully, this manual process can be streamlined and automated even more in the future, but for now it should already be a massive improvement over the previous one.
=> docs(CONTRIBUTING.md): add section on release management

CHANGELOG.md, pubspec.yaml
This PR prepares a new release that mostly performs some cleanup and improves the package documentation. However, there is also one new minor feature (the implementation of the `toJson` method).
=> chore(release): prepare release 0.28.4

lib/src/core/definitions/context.dart, lib/src/core/definitions/extensions/json_parser.dart, lib/src/core/definitions/thing_description.dart, lib/src/core/implementation/wot.dart, test/core/context_test.dart, test/core/definitions_test.dart, test/core/thing_description_test.dart
This PR improves the deserialization of the TD `@context`, and lays the groundwork for better enhancing the Thing Description objects and their components with context-provided information.
The new structure introduced here is probably an improvement to the one that existed before, however, further restructuring might be applied in the future, especially when it comes to using newer language features.
=> Rework TD @context handling

lib/src/core/definitions/context.dart, test/core/context_test.dart
This PR adds a shortcut for determining the default language code (if present) via the TD @context.
=> feat(context.dart): add getter for default language code

lib/src/core/implementation/consumed_thing.dart, lib/src/core/implementation/servient.dart, lib/src/core/implementation/wot.dart, test/core/consumed_thing_test.dart, test/core/wot_test.dart
In the context of #133, I have noticed that the `consume` method currently throws an exception if you want to consume the same Thing Description twice (or rather: two Thing Descriptions that have the same “identifier”), which can have unintended consequences when performing discovery.
This PR fixes the issue for now by changing the internal data structure from a `Map` to a `Set` and not checking for the presence of a Thing Description (using its `id` or `title`) anymore. This change is not really optimal and can only be considered a workaround, which I will properly fix as part of a general overhaul of the `Servient` API (which currently exposes too much API surface to the library user). That overhaul will be the next aspect of the library I will work on.
=> feat!: allow for consuming the same TD twice

.github/workflows/prepare-release.yaml
This PR adds a new GitHub Actions workflow that automates the procedure of creating new releases.
The workflow will check on each commit to the `main` branch if there are new changes that need to be added to the `CHANGELOG.md` file and, if so, commit them together with a corresponding version bump in the `pubspec.yaml` file. If there are changes, a Pull Request will be created that allows us to decide whether we want to create a new version or not based on the accumulated changes.
After merging this PR, there is only one final step of creating the new release after merging that needs to be added for a fully automated release procedure.
=> ci: automate release generation

CONTRIBUTING.md
This PR incorporates the improvements regarding the automation of the release process made in #143 into the `CONTRIBUTING.md` file.
There is still more work to be done and things can probably be solved a bit more elegantly – but I think this should be another major improvement to the overall process used in this repository :)
=> chore: update instructions for release management

.github/workflows/ci.yml
Related to https://github.com/eclipse-thingweb/.eclipsefdn/issues/18, this PR adds the CODECOV_TOKEN back as an argument for the codecov upload step into the respective workflow file.
As mentioned in https://github.com/eclipse-thingweb/.eclipsefdn/issues/18, the token should be updated, however, to point to the correct location on codecov itself (as currently, it is still referring to the namib-project there).
=> ci: add missing codecov token for code coverage determination

.github/workflows/prepare-release.yaml
This PR will probably incorporate the solution found in https://github.com/eclipse-thingweb/.eclipsefdn/pull/21, resolving the issues currently experienced in the context of #144.
=> chore: use Thingweb bot for release preparation

example/coap_discovery.dart, example/coap_dns_sd_discovery.dart, example/coaps_readproperty.dart, example/complex_example.dart, example/core_link_format_discovery.dart, example/directory_discovery.dart, example/example.dart, example/http_basic_authentication.dart, example/mqtt_example.dart, lib/src/core/implementation.dart, lib/src/core/implementation/consumed_thing.dart, lib/src/core/implementation/servient.dart, lib/src/core/implementation/thing_discovery.dart, lib/src/core/implementation/wot.dart, test/binding_http/http_test.dart, test/core/consumed_thing_test.dart, test/core/dart_wot_test.dart, test/core/discovery_test.dart, test/core/servient_test.dart, test/core/wot_test.dart
This PR reworks the API exposed by the `Servient`, making it more convenient and “safer” to use, by reducing the API surface that is exposed to library users.
In order to achieve this, I converted the `Servient` class into an abstract one, that instantiates a hidden `InternalServient` class via a factory constructor. This makes creating a new `Servient` a bit less “clean” since you need to call `create()` to instantiate the `Servient` now – but I think that is a tradeoff that is tolerable.
As a next step, the `InternalServient` as well as the implementations of the `ConsumedThing` and the `ExposedThing` interfaces can be improved internally. Furthermore, since all implementation details are now handled within the `InternalServient`, it should be easier to add new features, especially when …
=> feat!: rework Servient API

lib/src/binding_coap/coap_config.dart, lib/src/binding_mqtt/mqtt_client_factory.dart, lib/src/core/definitions/credentials/callbacks.dart, lib/src/core/definitions/extensions/json_parser.dart, lib/src/core/definitions/interaction_affordances/interaction_affordance.dart, lib/src/core/implementation/augmented_form.dart, lib/src/core/implementation/content_serdes.dart, lib/src/core/implementation/discovery/discovery_configuration.dart, lib/src/core/implementation/exposed_thing.dart, lib/src/core/implementation/protocol_interfaces/protocol_client_factory.dart, lib/src/core/implementation/servient.dart, lib/src/core/implementation/thing_discovery.dart
Inspired by @danielpeintner, I went through all the files with a spellchecker and found a number of typos and other smaller issues. This PR applies a first round of fixes to the documentation comments.
=> Fix documentation comments

lib/src/core/implementation/discovery/discovery_configuration.dart, lib/src/core/implementation/thing_discovery.dart
This PR adds an additional configuration for the `discover` method that makes it possible to automatically (re)discover TDs from a TDD. This can be useful to combine discovery from a directory with direct or mDNS discovery. Internally, the method simply calls the `exploreDirectory` method (without support for the `offset` parameter).
As the other discovery configurations, this has to be considered a bit experimental, it might be a useful addition, though.
=> feat(discovery): add ExploreDirectoryConfiguration for TDDs

.github/workflows/create-release.yml
Inspecting the release notes for the first fully automated release [0.31.0](https://github.com/eclipse-thingweb/dart_wot/releases/tag/v0.31.0), I noticed that the links included in the release notes used the wrong format (`0.31.0` instead of `v0.31.0`) for referencing the git tag associated with the release.
This PR applies a simple fix for that by slightly adjusting the GitHub Actions workflow definition.
=> ci: fix git tag reference automated GitHub releases

README.md
In https://github.com/eclipse-thingweb/dart_wot/pull/142, I forgot to update the example in the README file. This PR makes it usable again.
=> docs(README.md): use new Servient API in README example

lib/src/binding_mqtt/mqtt_client.dart
When trying to run the MQTT example, there was currently an error being thrown that stated that it “[c]annot fire new event. Controller is already firing an event” when the binding implementation was trying to call `disconnect` on the respective `MqttServerClient`.
This PR slightly alters the way the `disconnect` method is being thrown, thus solving the issue.
=> fix(binding_mqtt): fix disconnect of client after reading a resource

lib/src/core/scripting_api/subscription.dart
This PR fixes a small typo in a documentation comment.
=> docs(scripting_api): fix typo in Subscription interface

lib/core.dart, lib/src/core/implementation.dart, lib/src/core/implementation/consumed_thing.dart, lib/src/core/implementation/servient.dart, lib/src/core/implementation/thing_discovery.dart, lib/src/core/protocol_interfaces.dart, lib/src/core/protocol_interfaces/protocol_client.dart, lib/src/core/protocol_interfaces/protocol_client_factory.dart, lib/src/core/protocol_interfaces/protocol_server.dart
This PR reorganizes the project a bit by moving the `protocol_interfaces` up one level in the `core` directory.
=> refactor(core): create separate module for protocol_interfaces

lib/src/binding_coap/coap_subscription.dart, lib/src/binding_mqtt/mqtt_subscription.dart, lib/src/core/implementation/consumed_thing.dart, lib/src/core/implementation/servient.dart, lib/src/core/protocol_interfaces.dart, lib/src/core/protocol_interfaces/protocol_subscription.dart
This PR reworks the relationship between `Servient`, `ConsumedThing`, and the `Subscription`s created when observing a property or subscribing to an event. It also removes the `ConsumedThing` cleanup code from the `Servient` class, which is not needed anymore now.
These changes decrease the coupling between the different parts of the codebase, making it overall more maintainable.
=> Rework clean up of ConsumedThing

analysis_options.yaml
Since (almost) 100% of the public API members have documentation provided, this PR enforces the addition of new documentation a bit more strictly by reporting a warning instead of an info message if no doc comment should be provided.
This could even be changed to an error later if the API should become completely stable; however, as the development process is still ongoing, that step is probably a bit too much at the moment.
=> chore(analysis_options.yaml): report warnings for missing documentation

lib/src/core/scripting_api/interaction_input.dart
Via the [package score calculation](https://pub.dev/packages/dart_wot/versions/0.32.0/score) on pub.dev, I have noticed that there were a few documentation comments missing for the `InteractionInput` class. This PR closes gap and which bring `dart_wot` to 100% documentation coverage.
=> docs(scripting_api): add missing documentation for InteractionInput

lib/src/core/scripting_api/data_schema_value.dart
This PR fixes another small typo in a documentation comment.
=> docs(scripting_api): fix typo in DataSchemaValue documentation

lib/src/binding_coap/coap_client.dart, lib/src/binding_http/http_client.dart, lib/src/binding_mqtt/mqtt_client.dart, lib/src/core/protocol_interfaces/protocol_client.dart, test/core/discovery_test.dart
As a step towards adding #167, this PR changes the class modifier of the `ProtocolClient` class from `interface` to `class`, making it possible to specify certain (discovery) functionalities via mixins.
As they alter the API of the core library, these are breaking changes.
=> feat!: use base instead of interface for ProtocolClient class

example/coap_dns_sd_discovery.dart, lib/src/core/implementation/discovery/discovery_configuration.dart
This PR adds the `@immutable` annotation to the `DiscoveryConfiguration` base class and introduces `const` constructors in the class itself and its subclasses where possible.
=> feat: make DiscoveryConfiguration class immutable

lib/src/binding_coap/coap_extensions.dart, lib/src/binding_mqtt/mqtt_extensions.dart, lib/src/core/definitions/context.dart, lib/src/core/definitions/extensions/json_parser.dart, lib/src/core/definitions/operation_type.dart, lib/src/core/definitions/thing_description.dart, lib/src/core/exceptions.dart, lib/src/core/implementation/augmented_form.dart, lib/src/core/implementation/content_serdes.dart, lib/src/core/implementation/thing_discovery.dart, test/binding_coap/coap_definitions_test.dart, test/binding_mqtt/mqtt_extension_test.dart, test/core/augmented_form_test.dart, test/core/consumed_thing_test.dart, test/core/content_serdes_test.dart, test/core/context_test.dart, test/core/definitions_test.dart, test/core/exceptions_test.dart, test/core/thing_description_test.dart
This PR is a spin-off from #172, to make the changes a bit easier to track.
This PR replaces the custom `ValidationExeception` that is currently being used across the codebase with the built-in `FormatException`, which harmonizes the behavior during deserialization with other `parse` methods (e.g., `Uri.parse`).
=> feat!: use FormatException instead of custom ValidationException

lib/src/core/definitions/extensions/json_parser.dart
This PR fixes a bug related to the deserialization of Links that probably got introduced with the merge of #172.
=> fix(json_parser.dart): fix bug in link deserialization

test/core/content_serdes_test.dart
This PR addresses one left-over FIXME comment in one of the test files, where instead of the regular `DataSchema` constructor, the `fromJson` factory constructor was used (for some reason).
=> test(content_serdes_test.dart): address DataSchema FIXME comment

lib/src/core/definitions/data_schema.dart, lib/src/core/definitions/extensions/json_parser.dart
In the context of #180, I noticed two small bugs preventing a proper deserialization of TDs. Unfortunately, these problems have not been detected by the tests that are in place, so some improvements in that regard will be necessary in future PRs.
=> Fix DataSchema-related deserialization

example/coap_discovery.dart, example/coap_dns_sd_discovery.dart, example/core_link_format_discovery.dart, lib/src/core/implementation.dart, lib/src/core/implementation/servient.dart, lib/src/core/implementation/thing_discovery.dart, lib/src/core/implementation/wot.dart, lib/src/core/scripting_api.dart, lib/src/core/scripting_api/discovery/directory_payload_format.dart, lib/src/core/scripting_api/discovery/discovery_configuration.dart, lib/src/core/scripting_api/wot.dart
In the context of the recent discussion in the Scripting API repo, I realized that it probably makes more sense to pass the configurations for the `discover` method to the method itself, instead of setting them via the underlying `Servient`.
As there is still an ongoing discussion in the Scripting API taskforce, I labelled the changes as experimental, as there will probably be additional changes (that might lead to a totally different API than the one that is currently in place) as we go along.
=> feat!: move discovery configurations to scripting_api package

lib/src/core/definitions/interaction_affordances/property.dart, test/core/operation_type_test.dart
In the context of #182, I've noticed that additional properties have not been handled correctly during the deserialization of `Property` affordances. This PR fixes the issue and adjusts one test, as the constructor of the `Property` class had to be changed.
=> fix(property.dart): handle additional fields correctly

lib/src/core/implementation/servient.dart
As it is the case with the `Servient` class in `node-wot`, the `start` method in `dart_wot` is currently marked as `async`. This makes sense in general, as the start methods of the servers registered with the `Servient` are also asynchronous.
However, as the corresponding `init` method of the `ProtocolClientFactories`is _not_ asynchronous (at least in `dart_wot`), it would be possible to start the Servient synchronously and not require the surrounding environment to be `async` as well. Having such a synchronous, partial `start` method can therefore be beneficial for applications that only act as consumers.
To address this use case, this PR introduces a synchronous `startClientFactories` method that basically does what it advertises. It also applies some minor refactoring of the server …
=> Introduce `startClientFactories` method to Servient

.github/workflows/ci.yml
Since https://github.com/dart-lang/sdk/issues/55745 apparently has been resolved with the latest Dart SDK release, this PR removes the exception that was made for Windows.
=> ci: switch back to latest dart version on Windows

lib/src/core/definitions/thing_description.dart
Due to using the wrong format for commit messages indicating breaking changes in #191, the version in #190 did not get bumped correctly. This PR serves as a workaround (that won't be necessary again in the future).
=> style!(thing_description.dart: add a missing period

lib/src/binding_http/http_client.dart, lib/src/binding_http/http_client_factory.dart, lib/src/binding_http/http_config.dart
To be able to add additional trusted certificates to an `HttpClient`, this PR adjusts the binding implementation a little to allow for the creation of a custom internal `SecurityContext`, which can be enhanced with certificates that are included in an `HttpClientConfig`.
=> feat(binding_http): add possibility to define a custom SecurityContext

lib/src/binding_http/http_client.dart, lib/src/binding_http/http_config.dart
While #194 introduced the ability to set custom trusted certificates for the security contexts that are being created from the HTTP binding, it accidentally let the HTTP clients not use the default trusted root certificates of the underlying platform anymore. This PR fixes the issue by introducing a new config parameter, partly by using it in an appropriate place.
=> Reactivate `withTrustedRoots` by default in HTTP binding

lib/src/binding_http/http_client.dart, lib/src/binding_http/http_client_factory.dart, lib/src/binding_http/http_subscription.dart, pubspec.yaml, test/binding_http/http_client_factory_test.dart
This PR adds an initial implementation of server-sent events via the `sse_channel` package to the HTTP binding.
=> feat: add initial support for server-sent events

example/complex_example.dart, lib/src/binding_coap/coap_client.dart, lib/src/binding_coap/coap_client_factory.dart, lib/src/binding_coap/coap_definitions.dart, lib/src/binding_coap/coap_extensions.dart, test/binding_coap/coap_client_factory_test.dart, test/binding_coap/coap_definitions_test.dart
Via https://github.com/w3c/wot-binding-templates/pull/353, the `cov:observe` subprotocol has been removed from the CoAP binding template. This PR incorporates these changes by removing the code related to the now outdated subprotocol.
Currently, the polling behavior that is supposed to be used as a fallback as described in the binding template is not really supported yet, but I think this is something that should rather be added to the underlying CoAP library. I will investigate this in future PRs :)
=> feat(binding_coap)!: remove support for cov:observe subprotocol

example/tdd_discovery.dart, lib/src/core/definitions/extensions/json_parser.dart, lib/src/core/implementation/servient.dart, lib/src/core/implementation/thing_discovery.dart, test/core/discovery_test.dart
At the moment, discovery via the `exploreDirectory` method stops completely when an invalid TD is encountered during the discovery process.
This PR changes the logic for deserializing the discovered TDs into `ThingDescription` objects, making the process a bit more reliable, as invalid TDs are just being skipped now.
In order to help with debugging, one of the error message that is emitted during deserialization is also improved a bit and all errors during the directory discovery process will be logged via the developer tools.
=> Make directory discovery a bit more robust

lib/binding_coap.dart, lib/src/binding_coap/coap_client.dart, lib/src/binding_coap/coap_config.dart, pubspec.yaml
This PR adds some improvements to the handling of DTLS within the CoAP binding. To be able to merge this PR, a new version of the `coap` package has to be released first, therefore I am keeping this one a draft for now.
=> feat(binding_coap): add support for PEM root certificates

analysis_options.yaml, lib/src/binding_coap/coap_client.dart, lib/src/binding_http/http_client.dart, lib/src/binding_mqtt/mqtt_client.dart, lib/src/core/definitions/interaction_affordances/event.dart, lib/src/core/definitions/interaction_affordances/interaction_affordance.dart, lib/src/core/definitions/interaction_affordances/property.dart, lib/src/core/protocol_interfaces/protocol_client.dart, test/core/discovery_test.dart
Added [a new lint](https://dart.dev/tools/diagnostic-messages#always_put_required_named_parameters_first) and cleaned up the violations.
=> Required named parameters should be before optional named parameters.

analysis_options.yaml, lib/binding_coap.dart, lib/binding_http.dart, lib/binding_mqtt.dart, lib/core.dart, lib/src/core/definitions.dart, lib/src/core/definitions/interaction_affordances/interaction_affordance.dart, lib/src/core/extensions.dart, lib/src/core/implementation.dart, lib/src/core/scripting_api.dart
As of Dart 3.4 the official recommendation is to no longer use library names as outlined in this lint documentation: https://dart.dev/tools/linter-rules/unnecessary_library_name
This PR enables that lint and makes the necesarry adjustments.
=> Remove unnecessary library names
